title: PageObject
email: support@pageobject.org
description: Copyright © 2016 agido GmbH. All rights reserved.
baseurl: ""
url: "http://www.pageobject.org/"
github_username:  agido

# Build settings
markdown: kramdown
